### ISSUE TITLE
Unhandled 'error' event in node.js core.

### ISSUE THREAD

**Issue by bluerid** [jonfriesen/WhoAre#1]
I am getting this error from node's dns when I try to use this module. I am trying to use it in a loop..
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND whois.verisign-grs.com whois.verisign-grs.com:43
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

```
SitesArray.map(function( site, index ) {
    var parsed = parse(site.url);
    var regexp = /[a-z0-9-_]+.[a-z0-9]+$/g;
    var matches_array = parsed.host.match(regexp);

    whoare.you(matches_array[0], function(data) {
       console.log(data)
    });
});
```

**Comment by jonfriesen** [comment]
Thanks for opening an issue @bluerid I'll do my best to take a look this weekend and see if I can clear this issue up.

**Comment by jonfriesen** [comment]
Hi @bluerid I tested out WhoAre and am finding everything working normally with the test domains I have. Can you please provide some more information? A sample of what URLs are causing WhoAre to break would be very helpful.

**Comment by jonfriesen** [comment]
Closing as no response from post + cannot reproduce. Feel free to reach out if you come back!
